### PR TITLE
Use pkg not git for FreeBSD

### PR DESCRIPTION
**Pull request by Sp1l**
Port/pkg was released 2015-11-06

### CODE REVIEW

**Comment by kennwhite** [comment]
Appreciate this Bernard. I think we may need to explicitly check/add for the repo. This is what I get on 10-2R on AWS (ami-f709a29c) which is maintained by Colin Percival (http://www.daemonology.net/freebsd-on-ec2/):

> $ su - root -c 'pkg install -y py-letsencrypt sudo'
> Updating FreeBSD repository catalogue...
> FreeBSD repository is up-to-date.
> All repositories are up-to-date.
> pkg: No packages available to install matching 'py-letsencrypt' have been found in the repositories
> $ uname -a
> FreeBSD ip-10-0-0-54 10.2-RELEASE-p7 FreeBSD 10.2-RELEASE-p7 #0: Mon Nov  2 14:19:39
> UTC 2015  root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by Sp1l** [comment]
Oops... Probably 2 things going on here.
1. The package builders haven't packaged this just yet
2. Depending on the repo it may take a full quarter for the pkg to become available (2016Q1)

**Comment by kennwhite** [comment]
No problem. Is there a dev/preview repo we could point to? In the commit tree, I saw reference to ..security port & make install. Is that preferred?

**Comment by Sp1l** [comment]
Looks like it's in the "Latest" repo already
http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/py27-letsencrypt-0.0.0.d20151104.txz

Not so for the quarterly repo... http://pkg.freebsd.org/freebsd:10:x86:64/quarterly/All/

Not sure which one Colin uses in his EC2 image, can you check the URLs in the repo conf files?

**Comment by kennwhite** [comment]
I'll take a look.

**Comment by kennwhite** [comment]
No luck, but I'm admittedly in unknown territory with FreeBSD.

> root@ip-10-0-0-54:~ # pkg install http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/py27-letsencrypt-0.0.0.d20151104.txz
> Updating FreeBSD repository catalogue...
> FreeBSD repository is up-to-date.
> All repositories are up-to-date.
> pkg: No packages available to install matching 'http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/py27-letsencrypt-0.0.0.d20151104.txz' have been found in the repositories


> root@ip-10-0-0-54:~ # setenv PACKAGESITE "http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/"
> root@ip-10-0-0-54:~ # pkg install py27-letsencrypt
> Updating FreeBSD repository catalogue...
> FreeBSD repository is up-to-date.
> All repositories are up-to-date.
> pkg: No packages available to install matching 'py27-letsencrypt' have been found in the repositories


> root@ip-10-0-0-54:~ # ls -l /usr/local/etc
> total 20
> drwxr-xr-x  2 root  wheel   512 Nov  7 14:14 bash_completion.d
> drwxr-xr-x  5 root  wheel   512 Nov  7 14:14 periodic
> -rw-r--r--  1 root  wheel  2100 Nov  5 01:17 pkg.conf
> -rw-r--r--  1 root  wheel  2100 Nov  5 01:17 pkg.conf.sample
> drwxr-xr-x  2 root  wheel   512 Aug 12 15:55 rc.d
>
> root@ip-10-0-0-54:~ # cat /usr/local/etc/pkg.conf
> # System-wide configuration file for pkg(8)
> # For more information on the file format and
> # options please refer to the pkg.conf(5) man page
> 
> # Note: you don't need to have a pkg.conf file.  Many installations
> # will work well with no pkg.conf at all or with an empty pkg.conf
> # (other than comment lines).  You can also override any of these
> # settings from the environment.
> 
> # Configuration options -- default values.
> 
> #PKG_DBDIR = "/var/db/pkg";
> #PKG_CACHEDIR = "/var/cache/pkg";
> #PORTSDIR = "/usr/ports";
> #INDEXDIR = "";
> #INDEXFILE = "INDEX-10";        # Autogenerated
> #HANDLE_RC_SCRIPTS = false;
> #DEFAULT_ALWAYS_YES = false;
> #ASSUME_ALWAYS_YES = false;
> #REPOS_DIR [
> #    "/etc/pkg/",
> #    "/usr/local/etc/pkg/repos/",
> #]
> #PLIST_KEYWORDS_DIR = "";
> #SYSLOG = true;
> #ABI = "freebsd:10:x86:64";     # Autogenerated
> #DEVELOPER_MODE = false;
> #VULNXML_SITE = "http://vuxml.freebsd.org/freebsd/vuln.xml.bz2";
> #FETCH_RETRY = 3;
> #PKG_PLUGINS_DIR = "/usr/local/lib/pkg/";
> #PKG_ENABLE_PLUGINS = true;
> #PLUGINS [
> #]
> #DEBUG_SCRIPTS = false;
> #PLUGINS_CONF_DIR = "/usr/local/etc/pkg/";
> #PERMISSIVE = false;
> #REPO_AUTOUPDATE = true;
> #NAMESERVER = "";
> #HTTP_USER_AGENT = "Custom_User_Manager";
> #EVENT_PIPE = "";
> #FETCH_TIMEOUT = 30;
> #UNSET_TIMESTAMP = false;
> #SSH_RESTRICT_DIR = "";
> #PKG_ENV {
> #}
> #PKG_SSH_ARGS = "";
> #DEBUG_LEVEL = 0;
> #ALIAS {
> #}
> #CUDF_SOLVER = "";
> #SAT_SOLVER = "";
> #RUN_SCRIPTS = true;
> #CASE_SENSITIVE_MATCH = false;
> #IP_VERSION = 0
> 
> # Sample alias settings
> ALIAS              : {
>   all-depends: query %dn-%dv,
>   annotations: info -A,
>   build-depends: info -qd,
>   cinfo: info -Cx,
>   comment: query -i "%c",
>   csearch: search -Cx,
>   desc: query -i "%e",
>   download: fetch,
>   iinfo: info -ix,
>   isearch: search -ix,
>   prime-list: "query -e '%a = 0' '%n'",
>   leaf: "query -e '%#r == 0' '%n-%v'",
>   list: info -ql,
>   noauto = "query -e '%a == 0' '%n-%v'",
>   options: query -i "%n - %Ok: %Ov",
>   origin: info -qo,
>   provided-depends: info -qb,
>   raw: info -R,
>   required-depends: info -qr,
>   roptions: rquery -i "%n - %Ok: %Ov",
>   shared-depends: info -qB,
>   show: info -f -k,
>   size: info -sq,
>   }
> root@ip-10-0-0-54:~ # 
>

**Comment by kennwhite** [comment]
Getting closer. Not sure what to make of the py27-requests thing.

> root@ip-10-0-0-54:~ # pkg add http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/py27-letsencrypt-0.0.0.d20151104.txz
> Fetching py27-letsencrypt-0.0.0.d20151104.txz: 100%  217 KiB 222.6kB/s    00:01    
> Installing py27-letsencrypt-0.0.0.d20151104...
> pkg: Missing dependency 'py27-requests'
> 
> Failed to install the following 1 package(s): http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/py27-letsencrypt-0.0.0.d20151104.txz

**Comment by kennwhite** [comment]
This works, but I'm not sure what the typical convention/tolerance by users is for adding a Latest repo. Thoughts?

```
# mkdir -p /usr/local/etc/pkg/repos
# cat > /usr/local/etc/pkg/repos/FreeBSD.conf << 'EOF'
 FreeBSD: {
  url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"
 }
'EOF'
# pkg install py27-letsencrypt
...
   Installed packages to be UPGRADED:
    pkg: 1.6.1 -> 1.6.1_2

2 MiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching pkg-1.6.1_2.txz: 100%    2 MiB   2.5MB/s    00:01    
Checking integrity... done (0 conflicting)
[1/1] Upgrading pkg from 1.6.1 to 1.6.1_2...
[1/1] Extracting pkg-1.6.1_2: 100%
Message from pkg-1.6.1_2:
If you are upgrading from the old package format, first run:

  # pkg2ng
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 24 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
    py27-letsencrypt: 0.0.0.d20151104
    python2: 2_3
    py27-openssl: 0.15.1
    py27-cryptography: 1.0.2_2
    py27-enum34: 1.0.4
    py27-cffi: 1.2.1
    py27-pycparser: 2.10
    py27-idna: 2.0
    py27-ipaddress: 1.0.14
    py27-psutil: 3.2.2
    py27-requests: 2.8.1
    py27-pyrfc3339: 0.2
    py27-pytz: 2015.7,1
    py27-parsedatetime: 1.4
    py27-zope.interface: 4.1.2
    py27-configobj: 5.0.6_1
    py27-zope.component: 3.12.1
    py27-zope.event: 3.5.2_1
    py27-acme: 0.0.0.d20151104
    py27-werkzeug: 0.10.4
    py27-ndg_httpsclient: 0.4.0_1
    py27-mock: 1.0.1_1
    py27-python2-pythondialog: 3.3.0
    py27-configargparse: 0.9.3

The process will require 21 MiB more space.
3 MiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching py27-letsencrypt-0.0.0.d20151104.txz: 100%  217 KiB 222.6kB/s    00:01    
...
Fetching py27-configargparse-0.9.3.txz: 100%   16 KiB  16.8kB/s    00:01    
Checking integrity... done (0 conflicting)
[1/24] Installing py27-pycparser-2.10...
...
[24/24] Extracting py27-letsencrypt-0.0.0.d20151104: 100%
Message from py27-letsencrypt-0.0.0.d20151104:
===========================================================================

This software is a DEVELOPER PREVIEW intended for developers, testers and
early-adopters only. Support requests and bug reports should be sent directly
and only to the upstream project: https://github.com/letsencrypt/letsencrypt

letsencrypt is currently in Closed Beta (invite only). In order to
acquire certificates, you must have applied for and received an invitation,
and have your domains whitelisted FIRST.

This port installs the "standalone" Python client only, which does not use and
is not the letsencrypt-auto bootstrap/wrapper script.

By default, the client will authenticate and obtain certificates using, and
signed by a TEST(Staging) Certificate Authority (CA). These certificates will
NOT be trusted publicly.

To obtain certificates, use the --server argument pointing to the correct
server URL as documented in your invitation email, and use the 'certonly'
command as follows:

 # sudo letsencrypt --server <server-URL> certonly

Note: The client currently requires the ability to bind on TCP port 80. If
you have a server running on this port, it will need to be temporarily stopped
so that the standalone server can listen on that port to complete
authentication.

The letsencrypt plugins to support apache and nginx certificate installation
will be made available soon in the following ports:

 * Apache plugin: security/py-letsencrypt-apache
 * Nginx plugin: security/py-letsencrypt-nginx

===========================================================================
# 
```

**Comment by koobs** [comment]
Nice work @Sp1l!

**Comment by Sp1l** [comment]
In the default configuration this works just fine. It would be a user's action to switch to the quarterly security pkg repo. These people will understand the ramifications of using the quarterly repo.

I'd expect letsencrypt's code to have a pretty high change-rate over the coming months so using the quarterly pkg repo would be inadvisable as it only gets security fixes.

**Comment by kennwhite** [comment]
Merged with additional repo config wrapper. Thanks Bernard!

**Pull request closed without merging**
